name: saaaltodos
description: System for allocation, analysis and automation of labors.
publish_to: "none"
version: 2023.0.0+0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  # Flutter official tools.
  flutter:
    sdk: flutter
  ansicolor: ^2.0.1
  path: ^1.8.2

  # Locale support.
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Others.
  change_case: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # Enable material icons.
  uses-material-design: true

  # Enable generate code.
  generate: true
